export const MINISTRIES_DATA = [
  {
    id: "evangelism",
    title: "EVANGELISM",
    description: "We preach the Gospel of Jesus Christ to win souls and make disciples in all nations.",
    iconName: "cross",
    iconColor: "bg-[#8B1E1E]",
    titleColor: "text-[#8B1E1E]",
    lineColor: "bg-[#8B1E1E]",
    image: "https://images.unsplash.com/photo-1504052434569-7c9180859485?q=80&w=600",
  },
  {
    id: "discipleship",
    title: "DISCIPLESHIP",
    description: "We teach and equip believers to grow in faith, character, and purpose through sound biblical teaching.",
    iconName: "users",
    iconColor: "bg-[#D97706]",
    titleColor: "text-[#D97706]",
    lineColor: "bg-[#D97706]",
    image: "https://images.unsplash.com/photo-1529156069898-49953e39b3ac?q=80&w=600",
  },
  {
    id: "outreach",
    title: "OUTREACH TO RURAL COMMUNITIES",
    description: "We take the love of Christ to rural areas through evangelism, medical missions, relief materials, and support.",
    iconName: "outreach",
    iconColor: "bg-[#1E3A8A]",
    titleColor: "text-[#1E3A8A]",
    lineColor: "bg-[#1E3A8A]",
    image: "https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?q=80&w=600",
  },
  {
    id: "school-support",
    title: "BACK TO SCHOOL SUPPORT",
    description: "We provide school materials, uniforms, and support to children from less privileged families.",
    iconName: "school",
    iconColor: "bg-[#16A34A]",
    titleColor: "text-[#16A34A]",
    lineColor: "bg-[#16A34A]",
    image: "https://images.unsplash.com/photo-1497633762265-9d179a990aa6?q=80&w=600",
  },
  {
    id: "widows-care",
    title: "CARE FOR WIDOWS",
    description: "We show God's love by supporting widows through provision, counseling, and empowerment programs.",
    iconName: "widows",
    iconColor: "bg-[#7E22CE]",
    titleColor: "text-[#7E22CE]",
    lineColor: "bg-[#7E22CE]",
    image: "https://images.unsplash.com/photo-1544027993-37dbfe43562a?q=80&w=600",
  },
  {
    id: "orphans-care",
    title: "CARE FOR ORPHANS & LESS PRIVILEGED",
    description: "We provide for the needs of orphans and less privileged people through food, clothing, shelter, and education.",
    iconName: "orphans",
    iconColor: "bg-[#DC2626]",
    titleColor: "text-[#DC2626]",
    lineColor: "bg-[#DC2626]",
    image: "https://images.unsplash.com/photo-1509099836639-18ba1795216d?q=80&w=600",
  },
  {
    id: "prayer-intercession",
    title: "PRAYER & INTERCESSION",
    description: "We are committed to prayer, interceding for families, nations, and the body of Christ.",
    iconName: "prayer",
    iconColor: "bg-[#2563EB]",
    titleColor: "text-[#2563EB]",
    lineColor: "bg-[#2563EB]",
    image: "https://images.unsplash.com/photo-1543002588-bfa74002ed7e?q=80&w=600",
  },
  {
    id: "volunteer-partnership",
    title: "VOLUNTEER & PARTNERSHIP",
    description: "We partner with individuals, churches, and organizations to expand God's work and impact more lives.",
    iconName: "volunteer",
    iconColor: "bg-[#B45309]",
    titleColor: "text-[#B45309]",
    lineColor: "bg-[#B45309]",
    image: "https://images.unsplash.com/photo-1517486808906-6ca8b3f04846?q=80&w=600",
  },
];
