export const ROUTES = {
  HOME: "/",
  ABOUT: "/about",
  MISSION: "/mission",
  MINISTRY: "/ministry",
  MINISTRY_DETAIL: "/ministry/:id",
  EVENTS: "/events",
  EVENT_DETAIL: "/events/:id",
  CALENDAR: "/calendar",
  GALLERY: "/gallery",
  GALLERY_ALBUM: "/gallery/:id",
  SERMONS: "/sermons",
  SERMON_DETAIL: "/sermons/:id",
  CONTACT: "/contact",
  REGISTER: "/register",
  GIVE: "/give",

  ADMIN: "/admin",
  ADMIN_LOGIN: "/admin/login",
  ADMIN_DASHBOARD: "/admin/dashboard",
  ADMIN_EVENTS: "/admin/events",
  ADMIN_GALLERY: "/admin/gallery",
  ADMIN_SERMONS: "/admin/sermons",
  ADMIN_CALENDAR: "/admin/calendar",
  ADMIN_HOMEPAGE: "/admin/homepage",
  ADMIN_ABOUT: "/admin/about",
  ADMIN_SETTINGS: "/admin/settings",

  NOT_FOUND: "*",
};